# Site settings
title: yzernik.github.io
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  yzernik

# Build settings
markdown: kramdown
